ALTER TYPE "BodyMetric" ADD VALUE IF NOT EXISTS 'CHEST_WAIST_RATIO';

DO $$ BEGIN
  CREATE TYPE "BodyGoalType" AS ENUM ('LOSS', 'GAIN', 'MAINTAIN_ABOVE', 'MAINTAIN_BELOW');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TYPE "BodyGoalType" ADD VALUE IF NOT EXISTS 'MAINTAIN_ABOVE';
ALTER TYPE "BodyGoalType" ADD VALUE IF NOT EXISTS 'MAINTAIN_BELOW';

ALTER TABLE "BodyGoal"
  ADD COLUMN IF NOT EXISTS "goalType" "BodyGoalType" NOT NULL DEFAULT 'LOSS',
  ADD COLUMN IF NOT EXISTS "tolerance" DOUBLE PRECISION;
