DO $$ BEGIN
  CREATE TYPE "BodyGoalType" AS ENUM ('LOSS', 'MAINTAIN', 'GAIN');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "BodyGoal"
  ADD COLUMN IF NOT EXISTS "goalType" "BodyGoalType" NOT NULL DEFAULT 'LOSS',
  ADD COLUMN IF NOT EXISTS "tolerance" DOUBLE PRECISION;